model:
  h: 4
  encoder:
    text_hidden: 24
    text_size: 100
    layer: 2
    dropout: 0.5
    ffn_hidden: 512

  decoder:

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.01

logging:
  log_dir: logs
  log_freq: 100

checkpoint:
  save_dir: checkpoints
  save_freq: 1
